[build]
    publish="dist"
    functions="functions"

[[redirects]]
    from="/api/*"
    to="/.netlify/functions/:splat"
    status=200
    force = true

[[redirects]]
    from="/*"
    to="/index.html"
    status=200
    
[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "default-src 'self'; script-src 'strict-dynamic' 'unsafe-eval' 'unsafe-inline' https://encryptedlist.goatcounter.com; object-src 'none'; font-src https://cdn.jsdelivr.net; img-src https://ik.imagekit.io"
